### ISSUE TITLE
[Docs] Release v1.1.0 Release Notes

### ISSUE THREAD

**Issue by carlosmonteagudoinbibo** [Inbibo/adonisfx_docs#60]
Definition of Done:
- [x] List all the pull request merges made to development since March 25th.
- [x] Draft a first version of the release notes based on the previous list.
- [x] Polish the release notes.

**Comment by josevalverdeinbibo** [comment]
### No need to mention

- Merge pull request #1050 from Inbibo/#1006-dev-updateDevelopmentWithReleaseCandidate: https://github.com/Inbibo/adonisfx/pull/1050
Update development with rc.

- Merge pull request #1048 from Inbibo/#1006-dev-updateDevelopmentWithReleaseCandidate: https://github.com/Inbibo/adonisfx/pull/1048
Update development with rc.

- Merge pull request #1143 from Inbibo/#997-feat-maxSlidingDistanceFromBoundingBoxFinalMayaChanges: https://github.com/Inbibo/adonisfx/pull/1143
Final changes to max sliding distance from bbox, already mentioned.

- Merge pull request #1134 from Inbibo/revert-1133-#997-feat-maxSlidingDistanceFromBoundingBox: https://github.com/Inbibo/adonisfx/pull/1134
Revert "#997 Fixes for max slide distance warning dialog".

- Merge pull request #1151 from Inbibo/#1145-improve-portNormalizationFixesToDevelopment: https://github.com/Inbibo/adonisfx/pull/1151
Update dev with fixes made in rc.

- Merge pull request #1164 from Inbibo/#1103-feat-skinMergeDeformer: https://github.com/Inbibo/adonisfx/pull/1164
Rename render to final (AdnSkinMerge).

- Merge pull request #1176 from Inbibo/#1140-feat-slideOnGeometry: https://github.com/Inbibo/adonisfx/pull/1176
Plug renaming. Is there a need to mention it to work with older scenes?

### Bug Fixes

- Merge pull request #1045 from Inbibo/#1033-bug-specialCharactersInputName: https://github.com/Inbibo/adonisfx/pull/1045
(Fix) Filtered ASCII characters to get valid names for nodes and attributes in Linux. AdonisFX-1033

- Merge pull request #1047 from Inbibo/#1031-bug-checkSelectionPythonCreatorMethods: https://github.com/Inbibo/adonisfx/pull/1047
(Fix) Fixed Python runtime error due to incorrect element selection on node creation. AdonisFX-1031

- Merge pull request #1040 from Inbibo/#1034-bug-addColliderForceConnection: https://github.com/Inbibo/adonisfx/pull/1040
(Fix) Fixed error messages not displaying the proper status of the AdnSimshape connections. AdonisFX-1034

- Merge pull request #1042 from Inbibo/#1000-bug-angleNotDrawnOnAlignedInputs: https://github.com/Inbibo/adonisfx/pull/1042
(Fix) Fixed drawing of AdnLocatorRotation when the angle is 180º. AdonisFX-1000

- Merge pull request #1041 from Inbibo/#1032-bug-nothingExportedFileCreated: https://github.com/Inbibo/adonisfx/pull/1041
(Fix) Fixed exporter creating the AAD file when there is nothing to export or the only thing to export failed. AdonisFX-1032

- Merge pull request #1154 from Inbibo/#1147-fix-paintoolRemoveReferenceAdnWeightsDisplayNode: https://github.com/Inbibo/adonisfx/pull/1154
(Fix) Fixed manipulation of referenced nodes while using the AdonisFX paint tool. AdonisFX-1147

- Merge pull request #1159 from Inbibo/#1156-fix-forceToReconnectToDebugger: https://github.com/Inbibo/adonisfx/pull/1159
(Fix) Ask for a precise description. AdonisFX-1156

- Merge pull request #1158 from Inbibo/#506-fix-listHistoryOnReferencedNodes: https://github.com/Inbibo/adonisfx/pull/1158
(Fix) Fixed a bug that did not allow to add attachments on a AdnMuscle/AdnRibbonMuscle deformer created on referenced geometry. AdonisFX-506

- Merge pull request #1157 from Inbibo/#1155-bug-importWeightArrayIndexOutOfRange: https://github.com/Inbibo/adonisfx/pull/1157
(Fix) Fixed a bug in the handling of the constraint weight arrays. AdonisFX-1155

- Merge pull request #1173 from Inbibo/#1165-fix-cornerCaseIsPointInsideTriangle: https://github.com/Inbibo/adonisfx/pull/1173
(Fix) Fixed geometry sliding constraints not finding valid triangles to slide on for some vertices in very specific scenarios. AdonisFX-1165

- Merge pull request #1168 from Inbibo/#1146-fix-weightsNotConsolidatedFlood: https://github.com/Inbibo/adonisfx/pull/1168
(Fix) Fixed flood operation not working correctly for multi influence constraints. AdonisFX-1146

### Improvements

- Merge pull request #1170 from Inbibo/#1167-improve-optimizeAddDataToDebugDataNode: https://github.com/Inbibo/adonisfx/pull/1170
(Improve) Optimzed the initialization of the debugger improving the performance on scenes with many AdonisFX deformers. AdonisFX-1167

### New Features

- Merge pull request #1096 from Inbibo/#1095-feat-extendMenuCommonLinks: https://github.com/Inbibo/adonisfx/pull/1096
(Feat) Extended AdonisFX menu with Documentation, Tutorials and About sections. AdonisFX-1095

- Merge pull request #1098 from Inbibo/#802-feat-debuggerWithVisibility: https://github.com/Inbibo/adonisfx/pull/1098
(Feat) Added the ability to prevent the debugging of features if the geometry is not visible, hidden or isolated. AdonisFX-802

- Merge pull request #1121 from Inbibo/#997-feat-maxSlidingDistanceFromBoundingBox: https://github.com/Inbibo/adonisfx/pull/1121
(Feat) Added a warning dialog in AdnSkin when the "Max Sliding Distance" is considered too high for a mesh, which could freeze Maya. AdonisFX-997
(Feat) Added the ability to debug the Sliding Surface in AdnSkin. AdonisFX-997

- Merge pull request #1130 from Inbibo/#466-feat-maxSlidingDistanceWarning: https://github.com/Inbibo/adonisfx/pull/1130
(Feat) Added a warning dialog in AdnSimshape when the "Max Sliding Distance" is considered too high for a mesh, which could freeze Maya. AdonisFX-466
(Feat) Added the ability to debug the Sliding Surface in AdnSimshape. AdonisFX-466

- Merge pull request #1148 from Inbibo/#1081-feat-attachmentsToGeoMaya: https://github.com/Inbibo/adonisfx/pull/1148
(Feat) Added attachment to geometry constraints to AdnMuscle and AdnRibbonMuscle, allowing the muscle to be attached directly to the geometry of the bone. AdonisFX-1081

- Merge pull request #1153 from Inbibo/#1103-feat-skinMergeDeformer: https://github.com/Inbibo/adonisfx/pull/1153
(Feat) Added a new AdonisFX deformer in charge of merging the results given by skin simulation meshes and animation meshes into a final mesh. AdonisFX-1103

- Merge pull request #1161 from Inbibo/#1140-feat-slideOnGeometry: https://github.com/Inbibo/adonisfx/pull/1161
(Feat) Added slide on geometry constriants to AdnMuscle and AdnRibbonMuscle, allowing the muscle to slide directly on the geometry of the bone. AdonisFX-1140

- Merge pull request #1144 from Inbibo/#1079-feat-fullMassSupportToMuscleDeformers: https://github.com/Inbibo/adonisfx/pull/1144
(Feat) Added mass support for AdnMuscle and AndRibbonMuscle deformers, allowing better control to achieve the desired results. AdonisFX-1079
(Feat) Added point mass mode to AdonisFX deformers, which allows to specify either a mass per point or a density value from which point masses are computed. AdonisFX-1079

- Merge pull request #1162 from Inbibo/#1142-feat-importExportAttachmentsToGeo: https://github.com/Inbibo/adonisfx/pull/1162
(Feat) Add importer/exporter support for attachment to geometry and slide on geometry constraints. AdonisFX-1142
(Feat) Add importer/exporter support for the AdnSkinMerge deformer. AdonisFX-1142

**Comment by lucasferryinbibo** [comment]
CC: @carlosmonteagudoinbibo @josevalverdeinbibo @enriquemeseguerinbibo @luisalbaceteinbibo 

Here a quick reminder to:
- Document that now the shape preservation weight default is 0.0 for AdnMucles and AdnRibbonMuscle and update any related screenshots
- Document the changes related to the density conversion to g/cm3 and check if we have to change this description:
![image](https://github.com/Inbibo/adonisfx_docs/assets/107848821/a501c685-754d-4e0d-b047-adce12c8dc34)
- Document also the changes in the defaults of the Space Scale mode:
>> AdnMuscle and AdnRibbonMuscle: Forces
>> AdnSkin and AdnSimshape: Forces and Masses
- Update the release notes with the latest additions

Please list here anything else that might be missing

**Comment by lucasferryinbibo** [comment]
> CC: @carlosmonteagudoinbibo @josevalverdeinbibo @enriquemeseguerinbibo @luisalbaceteinbibo
> 
> Here a quick reminder to:
> 
> * Document that now the shape preservation weight default is 0.0 for AdnMucles and AdnRibbonMuscle and update any related screenshots. (DONE)
> * Document the changes related to the density conversion to g/cm3 and check if we have to change this description (TO BE DISCUSSED):
>   ![image](https://private-user-images.githubusercontent.com/107848821/339372632-a501c685-754d-4e0d-b047-adce12c8dc34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTA5NjMsIm5iZiI6MTcxODYxMDY2MywicGF0aCI6Ii8xMDc4NDg4MjEvMzM5MzcyNjMyLWE1MDFjNjg1LTc1NGQtNGUwZC1iMDQ3LWFkY2UxMmM4ZGMzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QwNzUxMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTdhMGVlOTEyY2I1YWRhMTRjNzM2ODIyNmQ4OGU0MTMyZjg0ZDlmOThmMTM5NzcxMDRkNzJjNDEwYjgxNmQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6CYIlDbulbhhtLaExjDPbwwtx1aGkkjTdxE4_733oMM)
> * Document also the changes in the defaults of the Space Scale mode: (DONE)
> 
> > > AdnMuscle and AdnRibbonMuscle: Forces
> > > AdnSkin and AdnSimshape: Forces and Masses
> 
> * Update the release notes with the latest additions (Currently in progress in PR [#60 Update release notes v1.1.0 #74](https://github.com/Inbibo/adonisfx_docs/pull/74))
> * Definition a typo in the shape preservation constraint description (DONE).
> * We also did some reordering for the paintable maps for all deformers and the debugger. (DONE)
> * We have also renamed Collision Constraints to Slide Collisions Constraints for the debugger in Simshape. (DONE)
> * Check animatable attributes for locators and sensors. (DONE)
> * Check this comment in case we want to modify the exposed units for density: [[Docs] Release v1.1.0 adonisfx#687 (comment)](https://github.com/Inbibo/adonisfx/issues/687#issuecomment-2152921167)
> 
> Please list here anything else that might be missing

Everything appears to be addressed except for the comment about the density units. We will decide how to proceed there
